- self:
  - repo:
      url: https://github.com/common-repo/upstream
      ref: v2.0.3
      with:
      - template-vars:
          GH_APP_KEY_SECRET: COMMON_REPO_BOT_PRIVATE_KEY
          GH_APP_OWNER: common-repo
          GH_APP_ID_SECRET: COMMON_REPO_BOT_CLIENT_ID
  - repo:
      url: https://github.com/common-repo/pre-commit
      ref: v1.0.1
      with:
      - yaml:
          source: .pre-commit-config.yaml
          dest: .pre-commit-config.yaml
          append: true

- repo:
    url: https://github.com/common-repo/pre-commit
    ref: v1.0.1
- include:
  - src/**
- rename:
    - from: ^src/(.*)$
      to: $1
